name: test
on:
  push:
    branches:
      - main
jobs:
  Check-out:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download AmpRed
        run: wget https://gitlab.com/chenwenphy/ampred/-/archive/main/ampred-main.tar.gz

      - name: Make Script Artifact
        run: tar -czvf Script.tar.gz *.wls

      - name: Upload Script Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Script
          path: Script.tar.gz

      - name: Upload AmpRed
        uses: actions/upload-artifact@v4
        with:
          name: ampred
          path: ampred-main.tar.gz
      

  fytcmma:
    runs-on: ubuntu-latest
    needs: Check-out
    container:
      image: fenyutanchan/fytcmma:14.1.0
      credentials:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Download Script Artifact
        uses: actions/download-artifact@v4
        with:
          name: Script
      
      - name: Download AmpRed
        uses: actions/download-artifact@v4
        with:
          name: ampred

      - name: Extract Artifact
        run: |
          tar -zxvf Script.tar.gz
          tar -zxvf ampred-main.tar.gz

      - name: Magic
        run: /bin/bash /root/magic.sh > /dev/null
      
      - name: Run HelloWorld
        run: wolframscript -file HelloWorld.wls

      - name: Run AmpRed-test
        run: wolframscript -file AmpRed-test.wls

      - name: Upload AmpRed-test Result
        uses: actions/upload-artifact@v4
        with:
          name: rslt.txt
          path: rslt.txt
