name: test
on:
  push:
    branches:
      - main
jobs:
  Check-out:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AmpRed-test.wls
          path: AmpRed-test.wls
      

  fytcmma:
    runs-on: ubuntu-latest
    needs: Check-out
    container:
      image: fenyutanchan/fytcmma:14.1.0
      credentials:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: AmpRed-test.wls
          path: AmpRed-test.wls

      - name: Magic
        run: /bin/bash /root/magic.sh > /dev/null
      
      - name: Run Script
        run: wolframscript -file AmpRed-test.wls

      - name: Upload Log
        uses: actions/upload-artifact@v4
        with:
          name: rslt.txt
          path: rslt.txt
