name: test
on:
  push:
    branches:
      - main
jobs:
  Check-out:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make Artifact
        run: tar -czvf Script.tar.gz *.wls

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Script
          path: Script.tar.gz
      

  fytcmma:
    runs-on: ubuntu-latest
    needs: Check-out
    container:
      image: fenyutanchan/fytcmma:14.1.0
      credentials:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: Script
          path: Script.tar.gz

      - name: Extract Artifact
        run: tar -zxvf Script.tar.gz

      - name: Magic
        run: /bin/bash /root/magic.sh > /dev/null
      
      - name: Run HelloWorld
        run: wolframscript -file HelloWorld.wls

      - name: Run AmpRed-test
        run: wolframscript -file AmpRed-test.wls

      - name: Upload HelloWorld Log
        uses: actions/upload-artifact@v4
        with:
          name: HW.log
          path: HW.log

      - name: Upload AmpRed-test Result
        uses: actions/upload-artifact@v4
        with:
          name: rslt.txt
          path: rslt.txt
